import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Bruh from './components/bruhComp'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'hello',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar/>
				<Bruh />
				{children}
			</body>
		</html>
	);
}
